### ISSUE TITLE
Why doesn't the AppleHDA binary file need to patch?

### ISSUE THREAD

**Issue by BeyondIM** [RehabMan/HP-Envy-DSDT-Patch#1]
I checked the patch_hda.sh, only found

ln -s /System/Library/Extensions/AppleHDA.kext/Contents/MacOS/AppleHDA AppleHDA_$1.kext/Contents/MacOS/AppleHDA

Why doesn't the AppleHDA binary file need to patch via bcc9's script? tks.

**Comment by RehabMan** [comment]
The binary is patched via Clover hotpatch in config.plist.
