### ISSUE TITLE
Possible minor typo for ENVY Q in makefile

### ISSUE THREAD

**Issue by luciorq** [RehabMan/HP-Envy-DSDT-Patch#4]
Hey @RehabMan,

I noticed a possible typo in the `makefile` when building the DSDT for the Q models. [link to line](https://github.com/RehabMan/HP-Envy-DSDT-Patch/blob/d8257e69ef7b35ba7872ff209e6123bdf0a97e25/makefile#L68)

I know that it don't affect the behavior since the is no file called `install_q`, but if you find it helpful I opened a pull request.
#3 

Thanks for the great work, you did a nice job tidying the project structure for the different models.

Have a great time!

**Comment by RehabMan** [comment]
merged your pull #3
